spring.application.name=M9_IndividualProject

# ===============================
# PostgreSQL DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/project_db
spring.datasource.username=pdnaranjo
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# API / SECURITY
# ===============================
server.error.include-message=never
logging.level.org.springframework.security=INFO

# Default demo accounts created on startup:
# admin / admin123
# user / user123
